[package]
name = "rusty_xmas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[profile.release]
#debug = true

[dependencies]
indicatif = "0.17.8"
itertools = "0.13.0"
rayon = "1.10.0"
serde_json = "1.0.117"
